### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by GsLogiMaker** [GsLogiMaker/qu-script#1]
- [x] - Improve external module definition API
- [x] - Improve external function API
- [x] - Implement class constructors
- [x] - Add boolean literals
- [x] - Add constants
- [x] - Fix functions with no parameters being un-callable
- [ ] - Prevent functions definitions from having multiple parameters of the same name
- [ ] - Add impl API
- [ ] - Add class definition syntax
- [ ] - Add class function definition syntax
- [ ] - Add sub-module definition syntax
- [ ] - Add simple constant evaluator to compiler
- [ ] - Add more discrete error types (ie ParserErr and CompilerErr instead of just QuMsg)
- [ ] - Replace instances of String with Ustr
- [ ] - Implement coroutines
- [ ] - Make constant function calls evaluated at compile time
- [ ] - Make all references to types in compiled code optimized away at runtime
